[oauth2]
google = { client_id = "119383028767-h283knlfs9dgh6pre9bb3em3vh69sevc.apps.googleusercontent.com", client_secret = "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",redirect_uri = "http://localhost:8501" }
